// <auto-generated />
using System;
using Folder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Folder.Migrations
{
    [DbContext(typeof(FolderContext))]
    [Migration("20230704091843_updateDatabase")]
    partial class updateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Folder.Models.Folders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParrentFolderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            FolderName = "Creating Digital Images"
                        },
                        new
                        {
                            Id = 5,
                            FolderName = "Resources",
                            ParrentFolderId = 4
                        },
                        new
                        {
                            Id = 6,
                            FolderName = "Evidence",
                            ParrentFolderId = 4
                        },
                        new
                        {
                            Id = 7,
                            FolderName = "Graphic Products",
                            ParrentFolderId = 4
                        },
                        new
                        {
                            Id = 8,
                            FolderName = "Primary Sources",
                            ParrentFolderId = 5
                        },
                        new
                        {
                            Id = 9,
                            FolderName = "Secondary Sources",
                            ParrentFolderId = 5
                        },
                        new
                        {
                            Id = 10,
                            FolderName = "Process",
                            ParrentFolderId = 7
                        },
                        new
                        {
                            Id = 11,
                            FolderName = "Final Product",
                            ParrentFolderId = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
